### PR TITLE
Add status of containers

### PR DESCRIPTION
**Pull request by WalentinG**
### Monitoring Docker container status using AWS CloudWatch
To enable monitoring use the flag `addcontainer`
The MetricName is **ContainerStatus** (Count) also there is dimension **ContainerName**
The value is **1** or **0** . Status map is presented bellow:
```
"running":    1,
"created":    0,
"restarting": 0,
"removing":   0,
"paused":     0,
"exited":     0,
"dead":       0,
```

### CODE REVIEW

**Comment by AndrianBdn** [comment]
Would be great to consider using official golang API - https://godoc.org/github.com/docker/docker/client 

Otherwise I would prefer to avoid calling docker for each container twice. I think it is possible to pass --format to "docker ps" and get specific parameters. If not, at least it should be possible to get docker-composer name and status in one call.

**Comment by WalentinG** [comment]
This official golang API is too big for our needs. Moreover, it is possible to obtain the name and status of containers by executing one command `docker inspect --format='%s,%s' $(docker ps -aq)`

**Comment by AndrianBdn** [comment]
Cool, thank you. Two minor points:
1) 'DockeInspect' — is it correct naming or you just missed "r" ?
2) I would prefer to specify in documentation that this is "docker-compose container status monitoring", not "docker container status monitoring" — because we're requesting docker-compose tag and I don't think it would work well for ordinary container.

**Comment by AndrianBdn** [comment]
Awesome, thank you 🎉 Hope it works well

**Pull request merged**
